os:
- linux
env:
  matrix:
  - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/
  global:
    secure: MFJHBZPW7DNtZ+lNRZU6g/l5T0Khc2J0kbQj7BZ/QtdyGLhkW4XcrS8lJ5Fbm/i96hc2sX+MXbrWRYDkuyE6u5dgIXIFL4X+KzAf19JpIBWfeRnZKL9b8/lOB7PN0WqPP0wNmB7mBi/2rgz31wt8yGU6pnk2UiWlHX77sT14PWE=
install:
- curl https://static.rust-lang.org/rustup.sh | sudo sh
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: 'curl https://raw.githubusercontent.com/iron-bot/build-doc/master/build-doc.sh
  | sh '
