[package]

name = "bodyparser"
authors = ["Patrick Tran <patrick.tran06@gmail.com>"]
version = "0.1.0"

[[lib]]

name = "bodyparser"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

