[package]

name = "bodyparser"
version = "0.0.5"
license = "MIT"
description = "Body parsing middleware for Iron."
repository = "https://github.com/iron/body-parser"
documentation = "http://ironframework.io/doc/bodyparser/index.html"
authors = ["Patrick Tran <patrick.tran06@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>"]
keywords = ["iron", "web", "http", "parsing", "parser"]

[dependencies]
iron = { version = "0.2", default-features = false }
rustc-serialize = "0.3"
plugin = "0.2"
persistent = "0"
